name: GitHub Actions Test
on: [pull_request]
jobs:
  upload_ts_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: DerYeger/yarn-setup-action@master
      - run: yarn
      - name: Get directory info
        run: ls
      # - id: coverage_upload
  #       shell: bash
  #       run: yarn ts-coverage > tsCoverage.txt
  #     - name: Upload TS Coverage
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: tsCoverage
  #         path: tsCoverage.txt
# -------------------------------------  
  download_artifacts:
    runs-on: ubuntu-latest
    needs: upload_ts_coverage
    steps:
      # - name: Generate TS Coverage Comment
      #   id: coverage_comment
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: tsCoverage
      # - shell: bash
      #   run: |
      #     coverage=`cat tsCoverage.txt`
      - name: Comment TS Coverage
        uses: actions/github-script@v6
     
        with:
          script: |
            let totalCoverage = 100;
            let msg = 'message before getting coverage'
            const getCoverage = require('./tsCoverage.js')
            const coverage = getCoverage().then(() => {
              totalCoverage = 20;
              msg = `TypeScript Coverage is at ${totalCoverage}%`
            })
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
# -------------------------------------  
